In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import make_scorer, accuracy_score, roc_auc_score
# from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [24]:
# loading the data
df_genre_clean = pd.read_csv("Resources/cleaned_data.csv")
df_genre_clean.head()

track_popularity  danceability  energy   key  loudness  mode  speechiness  \
0               1.0         0.748   0.916   6.0    -2.634   1.0       0.0583   
1               1.0         0.726   0.815  11.0    -4.969   1.0       0.0373   
2               1.0         0.675   0.931   1.0    -3.432   0.0       0.0742   
3               1.0         0.718   0.930   7.0    -3.778   1.0       0.1020   
4               1.0         0.650   0.833   1.0    -4.672   1.0       0.0359   

   acousticness  instrumentalness  liveness  valence    tempo  duration_ms  \
0        0.1020          0.000000    0.0653    0.518  122.036     194754.0   
1        0.0724          0.004210    0.3570    0.693   99.972     162600.0   
2        0.0794          0.000023    0.1100    0.613  124.008     176616.0   
3        0.0287          0.000009    0.2040    0.277  121.956     169093.0   
4        0.0803          0.000000    0.0833    0.725  123.976     189052.0   

   edm  latin  pop  r&b  rap  rock  
0    0      0    1    0    0     0  
1    0      0    1    0    0     0  
2    0      0    1    0    0     0  
3    0      0    1    0    0     0  
4    0      0    1    0    0     0

In [25]:
# Sampling our data to ensure we have balance set of data between train and test data

df_genre_clean = df_genre_clean.sample(frac = 0.8,random_state = 420)
df_genre_clean

track_popularity  danceability  energy   key  loudness  mode  \
27566               1.0         0.367   0.783   6.0    -4.504   1.0   
17762               0.0         0.333   0.456  10.0    -8.960   1.0   
543                 1.0         0.584   0.643   2.0    -6.415   1.0   
4003                1.0         0.802   0.645   5.0    -6.181   0.0   
8860                0.0         0.671   0.803   0.0    -7.497   0.0   
...                 ...           ...     ...   ...       ...   ...   
31487               0.0         0.661   0.935   7.0    -4.711   0.0   
28246               0.0         0.736   0.506  10.0   -12.549   0.0   
27383               0.0         0.798   0.832   0.0    -5.340   1.0   
3367                0.0         0.824   0.862   9.0    -5.213   0.0   
27423               0.0         0.742   0.223   4.0   -17.542   1.0   

       speechiness  acousticness  instrumentalness  liveness  valence  \
27566       0.1540       0.00515          0.000000    0.0545    0.289   
17762       0.0293       0.72500          0.000000    0.0921    0.331   
543         0.0395       0.28800          0.000000    0.1860    0.530   
4003        0.0715       0.27200          0.000000    0.1190    0.376   
8860        0.2920       0.05200          0.000248    0.1500    0.762   
...            ...           ...               ...       ...      ...   
31487       0.0796       0.00408          0.000825    0.0780    0.389   
28246       0.4020       0.75400          0.000001    0.4710    0.424   
27383       0.0916       0.16700          0.016900    0.1050    0.717   
3367        0.0403       0.00270          0.000201    0.0917    0.773   
27423       0.0658       0.95700          0.728000    0.1100    0.392   

         tempo  duration_ms  edm  latin  pop  r&b  rap  rock  
27566   88.013     192653.0    1      0    0    0    0     0  
17762  169.954     209529.0    0      1    0    0    0     0  
543     90.036     181844.0    0      0    1    0    0     0  
4003   100.001     157202.0    0      0    1    0    0     0  
8860   137.997     170013.0    0      0    0    0    1     0  
...        ...          ...  ...    ...  ...  ...  ...   ...  
31487  127.987     335613.0    1      0    0    0    0     0  
28246  124.015     230338.0    1      0    0    0    0     0  
27383  117.967     225890.0    1      0    0    0    0     0  
3367   128.001     390791.0    0      0    1    0    0     0  
27423   91.911     117395.0    1      0    0    0    0     0  

[26266 rows x 19 columns]

In [26]:
# Define features set


X=df_genre_clean.copy()
X=X.drop(columns=["track_popularity"])
X

danceability  energy   key  loudness  mode  speechiness  acousticness  \
27566         0.367   0.783   6.0    -4.504   1.0       0.1540       0.00515   
17762         0.333   0.456  10.0    -8.960   1.0       0.0293       0.72500   
543           0.584   0.643   2.0    -6.415   1.0       0.0395       0.28800   
4003          0.802   0.645   5.0    -6.181   0.0       0.0715       0.27200   
8860          0.671   0.803   0.0    -7.497   0.0       0.2920       0.05200   
...             ...     ...   ...       ...   ...          ...           ...   
31487         0.661   0.935   7.0    -4.711   0.0       0.0796       0.00408   
28246         0.736   0.506  10.0   -12.549   0.0       0.4020       0.75400   
27383         0.798   0.832   0.0    -5.340   1.0       0.0916       0.16700   
3367          0.824   0.862   9.0    -5.213   0.0       0.0403       0.00270   
27423         0.742   0.223   4.0   -17.542   1.0       0.0658       0.95700   

       instrumentalness  liveness  valence    tempo  duration_ms  edm  latin  \
27566          0.000000    0.0545    0.289   88.013     192653.0    1      0   
17762          0.000000    0.0921    0.331  169.954     209529.0    0      1   
543            0.000000    0.1860    0.530   90.036     181844.0    0      0   
4003           0.000000    0.1190    0.376  100.001     157202.0    0      0   
8860           0.000248    0.1500    0.762  137.997     170013.0    0      0   
...                 ...       ...      ...      ...          ...  ...    ...   
31487          0.000825    0.0780    0.389  127.987     335613.0    1      0   
28246          0.000001    0.4710    0.424  124.015     230338.0    1      0   
27383          0.016900    0.1050    0.717  117.967     225890.0    1      0   
3367           0.000201    0.0917    0.773  128.001     390791.0    0      0   
27423          0.728000    0.1100    0.392   91.911     117395.0    1      0   

       pop  r&b  rap  rock  
27566    0    0    0     0  
17762    0    0    0     0  
543      1    0    0     0  
4003     1    0    0     0  
8860     0    0    1     0  
...    ...  ...  ...   ...  
31487    0    0    0     0  
28246    0    0    0     0  
27383    0    0    0     0  
3367     1    0    0     0  
27423    0    0    0     0  

[26266 rows x 18 columns]

In [27]:
# Define target vector

y=df_genre_clean['track_popularity'].ravel()
y

array([1., 0., 1., ..., 0., 0., 0.])

In [28]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [35]:
X_train

danceability  energy   key  loudness  mode  speechiness  acousticness  \
30995         0.645   0.814   8.0    -5.934   0.0       0.0667      0.164000   
10552         0.505   0.908   2.0    -5.254   1.0       0.0483      0.006570   
7656          0.657   0.675   2.0    -5.536   1.0       0.0283      0.088800   
12271         0.530   0.864   4.0    -4.948   0.0       0.0610      0.000753   
10854         0.706   0.373   6.0   -12.610   0.0       0.3100      0.637000   
...             ...     ...   ...       ...   ...          ...           ...   
20976         0.746   0.915   8.0    -2.677   1.0       0.0502      0.138000   
13387         0.696   0.514  10.0    -7.899   0.0       0.0252      0.654000   
3495          0.267   0.787   2.0    -7.766   1.0       0.0428      0.006920   
1937          0.537   0.959   0.0    -3.002   0.0       0.0557      0.070400   
4760          0.676   0.788   9.0    -4.596   0.0       0.0428      0.100000   

       instrumentalness  liveness  valence    tempo  duration_ms  edm  latin  \
30995          0.000002    0.2130    0.519  145.036     190345.0    1      0   
10552          0.001850    0.5160    0.711  156.045     198120.0    0      0   
7656           0.000006    0.4440    0.883   88.021     251000.0    0      0   
12271          0.000459    0.3540    0.484  166.312     288533.0    0      0   
10854          0.000000    0.0993    0.827  204.031     117726.0    0      0   
...                 ...       ...      ...      ...          ...  ...    ...   
20976          0.094000    0.1220    0.939  124.032     242103.0    0      1   
13387          0.000004    0.3180    0.682   87.159     251587.0    0      0   
3495           0.505000    0.1800    0.268  130.039     316160.0    0      0   
1937           0.000002    0.3820    0.828  122.806     222707.0    0      0   
4760           0.254000    0.3260    0.688  123.018     253444.0    0      0   

       pop  r&b  rap  rock  
30995    0    0    0     0  
10552    0    0    1     0  
7656     0    0    1     0  
12271    0    0    0     1  
10854    0    0    1     0  
...    ...  ...  ...   ...  
20976    0    0    0     0  
13387    0    0    0     1  
3495     1    0    0     0  
1937     1    0    0     0  
4760     1    0    0     0  

[19699 rows x 18 columns]

In [31]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [32]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [33]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [34]:
X_train_scaled

array([[-0.0673396 ,  0.6361474 ,  0.73324171, ..., -0.44335312,
        -0.46329047, -0.42351975],
       [-1.03177175,  1.15460428, -0.92776662, ..., -0.44335312,
         2.15847308, -0.42351975],
       [ 0.01532602, -0.13050691, -0.92776662, ..., -0.44335312,
         2.15847308, -0.42351975],
       ...,
       [-2.67130642,  0.48722894, -0.92776662, ..., -0.44335312,
        -0.46329047, -0.42351975],
       [-0.81133012,  1.43589471, -1.48143606, ..., -0.44335312,
        -0.46329047, -0.42351975],
       [ 0.14621324,  0.49274444,  1.01007643, ..., -0.44335312,
        -0.46329047, -0.42351975]])

In [12]:
# Using LogisticRegression Model

LR_Model = LogisticRegression()
LR_Model.fit(X_train_scaled, y_train)
LR_Predict = LR_Model.predict(X_test_scaled)
LR_Accuracy = accuracy_score(y_test, LR_Predict)
print("Accuracy: " + str(LR_Accuracy))

LR_AUC = roc_auc_score(y_test, LR_Predict)
print("AUC: " + str(LR_AUC))

Accuracy: 0.6579869042180599
AUC: 0.5670614979660206


In [13]:
# Using RandomForestClassifier Model

RFC_Model = RandomForestClassifier()
RFC_Model.fit(X_train_scaled, y_train)
RFC_Predict = RFC_Model.predict(X_test_scaled)
RFC_Accuracy = accuracy_score(y_test, RFC_Predict)
print("Accuracy: " + str(RFC_Accuracy))

RFC_AUC = roc_auc_score(y_test, RFC_Predict)
print("AUC: " + str(RFC_AUC))

Accuracy: 0.7222476016445866
AUC: 0.6602656137832017


In [36]:
# comparing the predicted value to the actual value
predicted_value_df=pd.DataFrame({"Prediction": RFC_Predict, "Actual": y_test})

Prediction  Actual
0            0.0     0.0
1            1.0     1.0
2            0.0     0.0
3            0.0     1.0
4            0.0     1.0
...          ...     ...
6562         0.0     0.0
6563         0.0     0.0
6564         0.0     0.0
6565         0.0     0.0
6566         0.0     0.0

[6567 rows x 2 columns]

In [ ]:
# saving the predicted data
predicted_value_df.to_csv("Resources/predicted_data.csv", index=False)

In [14]:
# Random Forests in sklearn will automatically calculate feature importance
importances = RFC_Model.feature_importances_
# We can sort the features by their importance
sorted(zip(RFC_Model.feature_importances_, X.columns), reverse=True)

[(0.1000802910909335, 'loudness'),
 (0.0937044067834723, 'energy'),
 (0.09158796688498438, 'duration_ms'),
 (0.09112547890450523, 'tempo'),
 (0.08856195237296524, 'danceability'),
 (0.08849595624757009, 'acousticness'),
 (0.08723063311376412, 'valence'),
 (0.08550405581533002, 'speechiness'),
 (0.08285206578697742, 'liveness'),
 (0.08062544986013258, 'instrumentalness'),
 (0.048014736841708316, 'key'),
 (0.01416003136942381, 'edm'),
 (0.012694254094598685, 'mode'),
 (0.009423413291279567, 'pop'),
 (0.006850094221634882, 'rock'),
 (0.006669410987571789, 'rap'),
 (0.006263130167716919, 'latin'),
 (0.006156672165431259, 'r&b')]

In [15]:
# Using DecisionTree Model

DT_Model = DecisionTreeClassifier(max_depth=4)
DT_Model.fit(X_train_scaled, y_train)
DT_Predict = DT_Model.predict(X_test_scaled)
DT_Accuracy = accuracy_score(y_test, DT_Predict)
print("Accuracy: " + str(DT_Accuracy))

DT_AUC = roc_auc_score(y_test, DT_Predict)
print("AUC: " + str(DT_AUC))

Accuracy: 0.6377341251713111
AUC: 0.5725951184493898


In [16]:
import pickle


# save model
pickle.dump(RFC_Model, open('rf_model.pickle', "wb"))

In [17]:
# load model
loaded_rf_model = pickle.load(open('rf_model.pickle', "rb"))

# # you can use loaded model to compute predictions
rf_prediction = loaded_rf_model.predict(X_test_scaled)
rf_accuracy = accuracy_score(y_test, rf_prediction)
print("Accuracy: " + str(rf_accuracy))

rf_auc = roc_auc_score(y_test, rf_prediction)
print("AUC: " + str(rf_auc))

Accuracy: 0.7222476016445866
AUC: 0.6602656137832017


In [18]:
test=X_test_scaled[:1]
test

array([[-0.19133802, -1.12329667,  1.28691115, -1.49525014, -1.14085666,
         0.19472323,  1.02539218, -0.37687698, -0.76978025, -0.88586546,
        -0.03521327, -0.22990836,  2.10539978, -0.42635027, -0.45103583,
        -0.44335312, -0.46329047, -0.42351975]])

In [19]:
result=rf_prediction = loaded_rf_model.predict(test)
result

array([0.])